# Conexi�n a tu base de datos MongoDB Atlas
spring.mongodb.uri=mongodb+srv://sabrianouar2006_db_user:Anouar26_@tareachatdam.8gdtyeu.mongodb.net/chatdb?appName=TareaChatDam

# Puerto donde arrancar� tu servidor de Spring Boot
server.port=8080